# Generated by Django 5.0.1 on 2026-02-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_otpverification_userprofile_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_set_username',
            field=models.BooleanField(default=False),
        ),
    ]
