# Generated by Django 5.0.1 on 2026-03-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_group_created_by_alter_group_members_groupinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_drinker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_non_veg',
            field=models.BooleanField(default=False),
        ),
    ]
