# Generated by Django 5.0.1 on 2026-03-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_is_drinker_userprofile_is_non_veg'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='current_turn_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='member_order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
